### ISSUE TITLE
&amp displayed on empty folder

### ISSUE THREAD

**Issue by MichaelBailly** [OpenPaaS-Suite/esn-frontend-inbox#115]
![Capture d%u2019écran de 2020-09-04 11-59-53](https://user-images.githubusercontent.com/1465817/92246589-42361f80-eec6-11ea-91ea-3fb6a056925f.png)

**Comment by tlle14** [comment]
Duplicate with the translation issue in https://github.com/OpenPaaS-Suite/esn-frontend-inbox/issues/84

**Comment by tlle14** [comment]
Thank @pbson 

Retest pass!

![image](https://user-images.githubusercontent.com/69950655/92580404-83f50a80-f2b8-11ea-8b21-8db021d9197f.png)
