### ISSUE TITLE
Unable to save a draft 

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-inbox#116]
**Actual Result**

It is unable to save a draft. 

![error_draft](https://user-images.githubusercontent.com/69950655/92349203-911ac980-f0ff-11ea-9f05-e1fa3e9abb16.gif)

![image](https://user-images.githubusercontent.com/69950655/92349196-8bbd7f00-f0ff-11ea-8170-c5ab1cb7d71b.png)

**Expected result**

It should be able to save a draft

**Environment**

DEV environment

Chrome on Ubuntu

**Comment by tuanlc** [comment]
Hello @tlle14 
I cannot reproduce with my account tlcong@linagora.com on both production & dev platform.

Please re-test the feature.

**Comment by tlle14** [comment]
Thank @tuanlc 

The issue is no longer existing
