### ISSUE TITLE
Attachment sidebar is duplicated when change the window size

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-inbox#119]
**Actual Result**

When resizing the window, the "attachment" button is changing from "checked" to "uncheck".
The attachment sidebar is also unable to be closed.
 
![attachment](https://user-images.githubusercontent.com/69950655/92461770-d8828200-f1f3-11ea-8a0e-add211ae0e86.gif)

**Expected result**

Attachment button shouldn't change its state when resizing window

**Steps**

1. Click the attachment button to open the attachment sidebar
2. Resize the window
3. Click the attachment button again
4. Verify issue. 

**Environment**
Chrome on Ubuntu

**Comment by fabienmoyon** [comment]
Currently in a large device (XL : min-width: 1366px) on click we show/hide this sidebar by changing the route url specifically.

Proposition to fix that :

The best way is to no more change the route when we want to show/hide this sidebar in a large device. Like this we will only have one way for each device and size.
We will be able to hide the sidebar when we resize the app to a smaller and display the emails list in full view.

**Comment by tlle14** [comment]
Thank @fabienmoyon 
Retest pass on Desktop Chrome/Firefox Ubuntu
![Peek 2021-01-07 17-29](https://user-images.githubusercontent.com/69950655/103882317-31b0e280-510e-11eb-9920-454fdf78b2bb.gif)
