### ISSUE TITLE
%s attendees is displayed when looking at an event in Inbox

### ISSUE THREAD

**Issue by MichaelBailly** [OpenPaaS-Suite/esn-frontend-inbox#120]
![image](https://user-images.githubusercontent.com/1465817/92490878-d5869200-f1f1-11ea-972a-6132deb0fd05.png)

**Comment by tlle14** [comment]
Thank @pbson 

Retest pass!

On Dev platform:
![image](https://user-images.githubusercontent.com/69950655/92855265-4c06d800-f41c-11ea-8591-77c3c17b151d.png)

On Production platform:
![image](https://user-images.githubusercontent.com/69950655/92855439-75bfff00-f41c-11ea-98cc-c90f3922d5d3.png)

**Comment by tlle14** [comment]
Thank @pbson 

Retest pass

On Dev:
![image](https://user-images.githubusercontent.com/69950655/92857724-4959b200-f41f-11ea-9e6a-590c4b5a9c59.png)


On Production: Not yet deployed
