### ISSUE TITLE
Both the internal mail composer, and the mailto app, are triggered when clicking on the mail all attendees button of an event seen inside inbox

### ISSUE THREAD

**Issue by MichaelBailly** [OpenPaaS-Suite/esn-frontend-inbox#122]
**reproduction steps**
- have an event invitation response email
- click on "Event Details" in the blue bar
- click on the "mail attendees" button of the popin
![image](https://user-images.githubusercontent.com/1465817/92492662-e6380780-f1f3-11ea-8efc-89df5d34200c.png)

**Expected behaviour**
- a new embeded composer window opens, with in the `To` field the attendees of the event

**Actual behaviour**
- a new browser tab is opened with the mailto app 
- and also an embeded composer is open. Unfortunately it doesn't check for duplicate emails, so there is this error message in the console:
```
main.7ac95c4fa20b7befb92d.min.js:2 Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: tag in tagList.items track by track(tag), Duplicate key: (...)

```

**Comment by rezk2ll** [comment]
**bug** : the opInboxCompose directive is duplicate ( one from the mailto-handler and the other from the unifiedinbox module )
one directive opens the new composer newComposerService.open({ to: targets }); and the other does a $window.open(getMailtoUrl(targets), '_blank');.

so when the button is clicked, the 2 logics are fired at once.

**solution 1**: remove the mailto-handler dependency from the calendar module and handle the directives with ng-href="mailto:.. in the inbox module. in here i can decide whether to open a new composer or send the user to the mailto SPA ( if the directive has ng-href="mailto:..." property ).

**solution 2**: in the mailto-handler ignore the $window.open(getMailtoUrl(targets), '_blank'); part when there is no ng-href="mailto:... property.

**Comment by chamerling** [comment]
Well, the directives have the same name to be able to switch from one to the other easily:

- When in inbox, it must open the inbox composer
- When not in inbox, it must open the mailto application

If inbox has a dependency on calendar which has a dependency on mailto, you must exclude the dependency from calendar at the webpack level in inbox project
