### ISSUE TITLE
Can not find the button to send email when replying an email on mobile

### ISSUE THREAD

**Issue by chamerling** [OpenPaaS-Suite/esn-frontend-inbox#127]
When on mobile and replying to an email, I can not find the button to send the reply

**expected behavior**

Be able to send the reply

**screenshot**

![Screenshot_2020-09-09-22-54-28-003_com.android.chrome.jpg](https://user-images.githubusercontent.com/264403/92654544-401df780-f2f0-11ea-8333-43ff8a092908.jpg)

![Screenshot_2020-09-09-22-54-18-120_com.android.chrome.jpg](https://user-images.githubusercontent.com/264403/92654555-457b4200-f2f0-11ea-8254-b00d96957f38.jpg)

**platform**

Android 10, chrome 85

**Comment by piavgh** [comment]
This issue also happens in other places such as: `/unifiedinbox/configuration/vacation`

**Comment by piavgh** [comment]
## DoD:
The user should be able to see the Send button on the header when replying on an email

**Comment by tlle14** [comment]
Hi @piavgh 

Retest pass on ios/android mobile and tablet when replying or forwarding an email. 

![4855E611-5217-4536-803F-BAB53E8BD85D](https://user-images.githubusercontent.com/69950655/93197827-57d50000-f776-11ea-87c7-14201bc408bb.jpg)

![ADCC9D05-9A51-4F9C-A0E8-4FD677BC5336](https://user-images.githubusercontent.com/69950655/93197837-5acff080-f776-11ea-9270-4d03bd751bbe.jpg)
