### ISSUE TITLE
As a user, I can not see the email address of the email sender

### ISSUE THREAD

**Issue by chamerling** [OpenPaaS-Suite/esn-frontend-inbox#129]
Since the contact popover is not displayed anymore, the user is not able to have details about the email sender:

- Mouse over the sender display nothing
- Trying to reply to email does not display more information in the `To` field. The only way to get the email address is by looking at the quoted email...

cf screenshots for both

![Capture d’écran 2020-09-10 à 09 22 48](https://user-images.githubusercontent.com/264403/92694530-7cc90d80-f347-11ea-8f81-d1a60d869c5f.png)
![Capture d’écran 2020-09-10 à 09 22 56](https://user-images.githubusercontent.com/264403/92694552-85214880-f347-11ea-874f-816fae4f8013.png)

This information is useful in some situations, one of them is for example, to create filters based on the email address...

**Comment by MichaelBailly** [comment]
I don't want that we put the "popover" as it has been implemented.

Implement using the title attribute https://developer.mozilla.org/fr/docs/Web/HTML/Attributs_universels/title .

(`ng-attr-title="{{email}}"`)

**Comment by chamerling** [comment]
Agree to not put the popover back!

**Comment by fabienmoyon** [comment]
#### Description 

Can we also update the email sender to a link like this we will be able to have the native copy email address

#### Specs 

email sender must be a mailto link

**Comment by tlle14** [comment]
Thank @fabienmoyon 
Retest pass
![Peek 2021-02-25 16-07.gif](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/4a767c6a-5f98-46cc-84d9-d09e3eabecc5)
