### ISSUE TITLE
Filter input is broken for external email addresses

### ISSUE THREAD

**Issue by chamerling** [OpenPaaS-Suite/esn-frontend-inbox#132]
If the email is not an openpaas user, the display is broken: the x is below as shown here:

![Capture d’écran 2020-09-11 à 09 49 23](https://user-images.githubusercontent.com/264403/92886698-2544a380-f414-11ea-9b24-5ee94abb5d16.png)

Works well on contact

![Capture d’écran 2020-09-11 à 09 50 58](https://user-images.githubusercontent.com/264403/92886970-6c329900-f414-11ea-8624-0b39a6002a08.png)

**Comment by tlle14** [comment]
Thank @chamerling 

Retest pass on Dev Environment
![image](https://user-images.githubusercontent.com/69950655/93739358-48d8cc80-fc12-11ea-9148-4ec2914f3552.png)
