### ISSUE TITLE
Templates special folder is not translate

### ISSUE THREAD

**Issue by fabienmoyon** [OpenPaaS-Suite/esn-frontend-inbox#135]

**Comment by tlle14** [comment]
I cannot retest cause the Template mailbox is disabled on Frontend

**Comment by tlle14** [comment]
Thank @fabienmoyon 
Retest pass!
![image](https://user-images.githubusercontent.com/69950655/103988356-8ca31200-51c0-11eb-9827-1ef3144694e9.png)
