### ISSUE TITLE
FROM field is blank when REOPEN draft message

### ISSUE THREAD

**Issue by tuanlc** [OpenPaaS-Suite/esn-frontend-inbox#153]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7950991/93547045-5d0c9780-f98e-11ea-83f5-2b51561ec8e4.gif)

### Expected:
The default identity should be filled in FROM field by default

**Comment by tlle14** [comment]
Duplicate with https://github.com/OpenPaaS-Suite/esn-frontend-inbox/issues/75

**Comment by MichaelBailly** [comment]
Duplicate of #75, closing
