### ISSUE TITLE
Cannot connect with Linshare

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-inbox#155]
1. Open the composer
2. Click on Linshare icon

# Actual Result
Error log displays. Cannot connect to Linshare

# Expected Result
Linshare workspace should display

# Environment

Chrome on Ubuntu
DEV platform

**Comment by tuanlc** [comment]
Seems LinShare on dev platform does not works

**Comment by MichaelBailly** [comment]
correct. Never has
