### ISSUE TITLE
As a user, I want to see my folders list in a tree view

### ISSUE THREAD

**Issue by MichaelBailly** [OpenPaaS-Suite/esn-frontend-inbox#158]
Use a feature flag, and user can enable the tree view in configuration. This feature flag is recorded in broswer's localstorage.

**Comment by fabienmoyon** [comment]
Why this feature flag is recorded in broswer's localstorage and not in this user configuration like the identities ?

**Comment by fabienmoyon** [comment]
Technical links : 

- [material admin bootstrap lib](http://byrushan.com/projects/ma/1-5-2/angular/#/home) 
- [material.angularjs lib](https://material.angularjs.org/latest/)
- [angular-ui-tree lib - I think already used in to the filters page](https://github.com/angular-ui-tree/angular-ui-tree)
- [angularjs-tree libs](https://angularscript.com/file-explorer-like-angularjs-tree-view-directive/)

- [vuetifyjs v2 libs example](https://vuetifyjs.com/en/components/treeview/)

**Comment by tlle14** [comment]
The feature is under testing.
