### ISSUE TITLE
Remove "Unified Inbox" left sidebar icon

### ISSUE THREAD

**Issue by MichaelBailly** [OpenPaaS-Suite/esn-frontend-inbox#159]

**Comment by tlle14** [comment]
Please notice when creating a top-level folder 
![image](https://user-images.githubusercontent.com/69950655/94249778-91fa8a80-ff4a-11ea-8d04-f05341dda54e.png)

**Comment by fabienmoyon** [comment]
INBOX of the default user account will be the folder selected by default in the interface.

Is it the expected display and result you want @MichaelBailly ? 


![Capture d’écran de 2020-11-04 10-51-23](https://user-images.githubusercontent.com/11298249/98096310-e3703080-1e8b-11eb-8782-e1b661463863.png)

**Comment by fabienmoyon** [comment]
> Please notice when creating a top-level folder
> ![image](https://user-images.githubusercontent.com/69950655/94249778-91fa8a80-ff4a-11ea-8d04-f05341dda54e.png)

Have a empty folder is weird 

![Capture d’écran de 2021-01-22 11-51-22](https://user-images.githubusercontent.com/11298249/105482087-3518a200-5ca8-11eb-9e99-f089ea4a24e3.png)
