### ISSUE TITLE
Display incorrect mailbox name in frontend 

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-inbox#164]
# Actual Result
Frontend cannot display special character correctly. Example: `<` `>` `&`
![image](https://user-images.githubusercontent.com/69950655/93863887-4cda1c80-fcee-11ea-8583-bc3053a37779.png)

# Expected Result
The character that is allowed to display on frontend should be display correctly

# Environment
DEV platform

**Comment by tlle14** [comment]
Thank @MichaelBailly 

Retest pass
![image](https://user-images.githubusercontent.com/69950655/95410455-323eaf00-094e-11eb-8d30-ac3a55e3d323.png)

**Comment by MichaelBailly** [comment]
Impact analyses: this PR kind of relaxes security constraints. The tester should look for malicious folder names that may be transformed into javascript code.
