### ISSUE TITLE
"Propose new time" throws error

### ISSUE THREAD

**Issue by chamerling** [OpenPaaS-Suite/esn-frontend-inbox#167]
When clicking on "Propose new time" button in the email bluebar, the following exception is displayed:

![Capture d’écran 2020-09-23 à 14 26 00](https://user-images.githubusercontent.com/264403/94012279-db12d900-fda8-11ea-80be-8e099d836160.png)

This can be fixed by adding the `ngInject` annotation in the modal call.

## Expected

Displays the event modal which propose new time

**Comment by MichaelBailly** [comment]
cannot reproduce
