### ISSUE TITLE
back button is broken

### ISSUE THREAD

**Issue by MichaelBailly** [OpenPaaS-Suite/esn-frontend-inbox#17]
display an email, click the back arrow button: nothing happens.

Tests:

* I'm in inbox, I look at an email, I click on the back arrow: I'm in inbox
* I search for emails, I look at an email, I click on the back arrow: I'm in the search result page

Tips: module=esn.previous-page, directive=esnBackButton

**Comment by huy-ta** [comment]
I'm not sure about this issue. The tests you provide yield no bug for me.

The bug only arises when there's no history/previous state(s). For example, you open an email and copy-paste that link to a new tab, and then click the back button in the subheader, then you will redirected to `/unifiedinbox` - an empty page.

![Screenshot from 2020-07-28 17-12-22](https://user-images.githubusercontent.com/24670327/88652846-8b3fca80-d0f5-11ea-96f3-d746093b0653.png)

**Comment by piavgh** [comment]
I also can not reproduce this issue
