### ISSUE TITLE
Redundant search icon 

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-inbox#172]
# Actual Result

The small search icon is displaying next to the filter in each mailbox.
When a user put a keyword in the search box, it calls a lot of requests (which has the limit of 30 emails/request) to scan all emails in the mailbox. 
![image](https://user-images.githubusercontent.com/69950655/94245779-f581b980-ff44-11ea-8381-886e371c398e.png)

# Expected Result
Confirm if we should remove that icon. 

# Environment
Production

**Comment by MichaelBailly** [comment]
We will not remove that icon.
