### ISSUE TITLE
Enable to unselect `read receipts` if I don't click outside the Email writing window

### ISSUE THREAD

**Issue by fabienmoyon** [OpenPaaS-Suite/esn-frontend-inbox#173]
# reproduction steps

- Go to inbox
- click on new email FAB
- click on the three vertical dots at the left of the **send** button
- [a dialog appear, with "Request a read receipt"]
- click outside

**CURRENT**

the dialog does not close

**EXPECTED**

the dialog closes

**Comment by fabienmoyon** [comment]
After investigation this is due to the `z-index` between `box-overlay-container` (1050) and `md-backdrop` (99) so `read receipts` menu is closed only if we click outside of the `box-overlay-container` (more or less outside of the composer). 
Explication here : https://stackoverflow.com/questions/34900067/angular-material-md-menu-element-does-not-close-if-clicked-outside-on-a-fixed-el

Options to resolve this : 
1) Close the `read receipts` menu on leave of the menu like here https://codepen.io/fabienmoyon/pen/dypvmKa
2) Try to play with the position between `box-overlay-container` (1050) and `md-backdrop` (99) to have the `md-backdrop` upper the `box-overlay-container` BUT can impact many other major z-index component like sidebar, modal etc

**Comment by tlle14** [comment]
Thank @fabienmoyon 
It works on both Chrome and Firefox Ubuntu. 
Sometimes it doesn't. I cannot find a way to reproduce. So now the fix is acceptable. 
![Peek 2021-01-06 17-24](https://user-images.githubusercontent.com/69950655/103758484-d666ed80-5044-11eb-805a-9e810223e67d.gif)
