### ISSUE TITLE
As an user I want to see the full date in the email date displayed

### ISSUE THREAD

**Issue by fabienmoyon** [OpenPaaS-Suite/esn-frontend-inbox#174]
Full date support in email list view.

![image-82](https://user-images.githubusercontent.com/11298249/106595674-31143c00-6554-11eb-841b-4f0e0426b6a4.png)

## CURRENT

no title to see the full date of each email in the emails list

## EXPECTED 

have a title to see the full date of each email in the emails list

**Comment by fabienmoyon** [comment]
I added a tooltip to display the full date on each date.

What do you think @MichaelBailly  and @chamerling about the proposition made by Harold ? 


The date section will be more larger (110px to 130px)  because the time in EN have the AM or PM indicator.

#### CURRENT

![Capture d’écran de 2021-02-11 17-33-24.png](https://images.zenhubusercontent.com/5f9c1883317e52f28f3396ce/ac6d5d2a-dffb-4f2d-a886-248e66f4be1f)

#### SPEC

 ![Capture d’écran de 2021-02-11 12-03-47.png](https://images.zenhubusercontent.com/5f9c1883317e52f28f3396ce/99d817ff-4ed0-4561-8123-f93207a0bfb7)

**Comment by tlle14** [comment]
Thank @fabienmoyon 
Retest pass!

- It seems the time displays for days within a week.
- And the time tooltip displays when hovering on the date.
![Peek 2021-02-25 16-11.gif](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/08c6a75b-7392-4038-8deb-c1736f37d7b4)

**Comment by tlle14** [comment]
Thank @fabienmoyon 
Retest pass!

- It seems the time displays for days within a week.
- And the time tooltip displays when hovering on the date.
![Peek 2021-02-25 16-11.gif](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/08c6a75b-7392-4038-8deb-c1736f37d7b4)
