### ISSUE TITLE
[DropDrag] The view does not update correctly

### ISSUE THREAD

**Issue by tuanlc** [OpenPaaS-Suite/esn-frontend-inbox#182]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7950991/94418994-519a4700-01ac-11eb-9ef0-5167f0daa832.gif)

As you see at the gif demo, after drag&drop an invitation event in the list INBOX to trash, the `Github notification` email view is updated with `ICS/Calendar` icon. However, it should not be there.

The bug disappears after refreshing.

**Comment by MichaelBailly** [comment]
This issue have to be re-tested after the merge of OpenPaaS-Suite/esn-frontend-inbox/pull/185

**Comment by MichaelBailly** [comment]
Impact analyses is here https://github.com/OpenPaaS-Suite/esn-frontend-inbox/issues/181#issuecomment-701383254

**Comment by tlle14** [comment]
Hi @MichaelBailly 

Retest pass - the issue is not able to reproduce anymore

![Peek 2020-10-09 10-13](https://user-images.githubusercontent.com/69950655/95541487-bf9d0480-0a1d-11eb-831d-e0631a917f2b.gif)
