### ISSUE TITLE
Blank message list when mailbox/folder can not be found

### ISSUE THREAD

**Issue by chamerling** [OpenPaaS-Suite/esn-frontend-inbox#186]
I just had issue after today update on our production deployment: Message list was blank while folders were displayed on the right side.

![Capture d’écran 2020-09-30 à 15 18 40](https://user-images.githubusercontent.com/264403/94690320-41ab7000-0330-11eb-9c11-f511ce0320f1.png)

For some reason I have been redirected to https://<HOST>/inbox/#/unifiedinbox/ which displays this screen.
There are no errors in the console.

If from the address bar I enter something like https://<HOST>/inbox/#/unifiedinbox/foobar and `foobar` does not exists, user is redirected to https://<HOST>/inbox/#/unifiedinbox/inbox. I expect that being at https://<HOST>/inbox/#/unifiedinbox/ also redirect to https://<HOST>/inbox/#/unifiedinbox/inbox, but it does not, then the blank message screen is displayed.

**Comment by MichaelBailly** [comment]
needs to work on the ui-router states.

Another way of triggering the issue:

- go to Inbox
- open an email
- F5 (refresh page)
- click on the **back** arrow button

Expected: arriving somewhere

Current: arriving nowhere

**Comment by chamerling** [comment]
Right, this is what happened to me: I was on an email, F5, then click on the back button.

**Comment by alagane** [comment]
It seems the `deepStateRedirect` is malfunctioning, the same problem happens when the user goes to configuration where they should be redirected to the vacation tab, or in contacts where they should be redirected to the addressbook.

**Comment by alagane** [comment]
Introduced in https://github.com/OpenPaaS-Suite/esn-frontend-inbox/commit/06ce8d5

**Comment by alagane** [comment]
Related PR: https://github.com/OpenPaaS-Suite/esn-frontend-inbox/pull/318

**Comment by tlle14** [comment]
Thank @alagane 
Retest pass!

**No more blank page**
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/7a7e2ff4-7254-49d9-8e67-a0ebc9d576c3)

**No more back to nowhere**
![Peek 2021-02-25 15-15.gif](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/b897e4d6-c656-45e0-811d-9fbcdecf6a5e)
