### ISSUE TITLE
Mailbox name doesn't display in the message dialog

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-inbox#188]
# Actual Result
When deleting a mailbox, it opens a dialog with an invalid mailbox name 

![image](https://user-images.githubusercontent.com/69950655/94786820-ad0e4400-03fb-11eb-8d51-58be973e4d41.png)

# Expected Result

The dialog should display the correct mailbox name

**Comment by tlle14** [comment]
Thank @MichaelBailly 

Retest pass!

![image](https://user-images.githubusercontent.com/69950655/95408666-349f0a00-094a-11eb-9840-f83d95808665.png)

**Comment by MichaelBailly** [comment]
Impact analyses:

This has to be noted that Inbox got a highly specific message for folder. Here are the cases to test:

1/ delete a folder
2/ delete a folder containing 3 folders
3/ delete a folder containing 4 folders
4/ delete a folder containing 6 folders

**Comment by tlle14** [comment]
`&` and `<   >`character cannot display well on the dialog message

![image](https://user-images.githubusercontent.com/69950655/95445476-4522a500-0989-11eb-991e-dfd98ac63e8c.png)
![image](https://user-images.githubusercontent.com/69950655/95447257-ab102c00-098b-11eb-9ddf-d5f7fcf7e28c.png)

**Comment by MichaelBailly** [comment]
@tlle14 this has been fixes, I just re-tested on dev platform. Can you check and maybe close ?

**Comment by tlle14** [comment]
Thank @MichaelBailly 

Retest pass on Production
![image](https://user-images.githubusercontent.com/69950655/103887156-3331d900-5115-11eb-9ef6-8f8dde1f5762.png)
![image](https://user-images.githubusercontent.com/69950655/103887212-447ae580-5115-11eb-8b4c-9f406439d53d.png)
![image](https://user-images.githubusercontent.com/69950655/103887264-5b213c80-5115-11eb-971a-232ff6f39602.png)
