### ISSUE TITLE
Mobile > cannot create a mailbox on mobile because the creation dialog is hidden

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-inbox#213]
# Actual Result
When user creating a new mailbox, the "create a new folder" dialog is hidden
![android_mailbox](https://user-images.githubusercontent.com/69950655/95745342-21c86480-0cbf-11eb-8719-f8c0a0de7934.jpeg)

# Expected Result
The dialog should be aligned in the center

# Environment
DEV environment
iPhoneX - Safari, Chrome
Samsung A5 - Chrome

**Comment by alagane** [comment]
It seems the bug is fixed on dev, but not yet on our production openpaas, can you confirm?

**Comment by tlle14** [comment]
@alagane Retest failed on Production. Could you check if we missed the branch?

**Comment by alagane** [comment]
Ok, so this problem seems related to https://github.com/OpenPaaS-Suite/esn-frontend-calendar/commit/6fa35a44628c2bce6b61471ce9bf493f895419af#diff-33b0ebf5f5f4575c0a954733fa2635b04918693b4a9227e2ee56d693e05bfc0fR297 (on esn-frontend-calendar)

**Comment by tlle14** [comment]
@renaudboyer @huy-ta  Please corporate to fix this issue
