### ISSUE TITLE
All preview messages have been underline when opening a reply composer with a special signature.

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-inbox#218]
# Actual Result
On Production, when clicking reply to an email with a special signature, then back to the message list, all the preview text in the list has been highlighted
![image](https://user-images.githubusercontent.com/69950655/96421338-dc58e980-1220-11eb-98d5-e938065a1da0.png)

![Peek 2020-10-19 15-23](https://user-images.githubusercontent.com/69950655/96421006-6bb1cd00-1220-11eb-84b9-ea3dbbce78ce.gif)

# Expected Result

Please investigate. 
The preview text shouldn't be highlighted.

# Environment
Production

**Comment by tlle14** [comment]
eml file
[Check mail.zip](https://github.com/OpenPaaS-Suite/esn-frontend-inbox/files/5401028/Check.mail.zip)

**Comment by fabienmoyon** [comment]
Related issues : https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.unifiedinbox/issues/946 & 
https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.unifiedinbox/issues/939

**Comment by oubchid** [comment]
I didn't find btn to upload eml file can someone know where ?

**Comment by tlle14** [comment]
Thank @oubchid  @MichaelBailly 

Retest pass on DEV platform
![image](https://user-images.githubusercontent.com/69950655/100203251-ee6f2b80-2f34-11eb-9314-fea614db8c90.png)

**Comment by tlle14** [comment]
Hi @oubchid @MichaelBailly 
The special signature is affecting the configuration tab name. You can see in the below photo:
![image](https://user-images.githubusercontent.com/69950655/100208569-71938000-2f3b-11eb-8452-4e0dd2ec4103.png)

**Comment by oubchid** [comment]
Hi @tlle14 

Fixed here https://github.com/OpenPaaS-Suite/esn-frontend-inbox/pull/307

**Comment by tlle14** [comment]
I don't see it changed. Please recheck. 

![image](https://user-images.githubusercontent.com/69950655/102846578-e5de1800-4442-11eb-92ad-e7d4767b4848.png)

**Comment by oubchid** [comment]
@tlle14 
weird behavior, less file updated, but the CSS generated didn't take care of this modification  ...
I will investigate it.

**Comment by oubchid** [comment]
Fixed in production, after software deployment today.

*Messages list*
![image](https://user-images.githubusercontent.com/7097550/103765748-fcc56280-501d-11eb-91d8-c13f7c33e75d.png)

*Configuration tab*
![image](https://user-images.githubusercontent.com/7097550/103765585-afe18c00-501d-11eb-924b-42ac9832749c.png)

**Comment by tlle14** [comment]
Thank @oubchid 
Retest pass on Production
![image](https://user-images.githubusercontent.com/69950655/103871264-6c5f4e80-50ff-11eb-8e2d-2ce71ad3b352.png)
![image](https://user-images.githubusercontent.com/69950655/103871286-74b78980-50ff-11eb-8807-ec208ef46fbb.png)
