### ISSUE TITLE
[i18n] inject translations

### ISSUE THREAD

**Issue by MichaelBailly** [OpenPaaS-Suite/esn-frontend-inbox#22]
Details [here](https://ci.linagora.com/linagora/lgs/openpaas/esn/-/wikis/Frontend-Split/Polish/i18n#code-changes-howto-solution-1-kiss)

**Comment by tuanlc** [comment]
Correct the translation from this [PR](https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.unifiedinbox/merge_requests/497)
