### ISSUE TITLE
Composer: Weird behavior with recipient autofill

### ISSUE THREAD

**Issue by chamerling** [OpenPaaS-Suite/esn-frontend-inbox#225]
## Behavior

When user wants to add email recipient, the browser autofill is displayed on top of the selector 

![Capture d’écran 2020-10-26 à 14 41 56](https://user-images.githubusercontent.com/264403/97180133-f606ad80-1799-11eb-87ba-4ebbc0bf8800.png)

If user puts is mouse over the browser autofill, the email is displayed in all To, CC, BCC fields

![Capture d’écran 2020-10-26 à 14 42 02](https://user-images.githubusercontent.com/264403/97180302-2c442d00-179a-11eb-961e-5af205805450.png)

If finally clicked, here is how it is displayed

![Capture d’écran 2020-10-26 à 14 42 10](https://user-images.githubusercontent.com/264403/97180370-4251ed80-179a-11eb-9eb3-c29ff44878f9.png)

## Expected

I guess, none of the above

## Platform

Occured on OS X, Chrome 86

**Comment by oubchid** [comment]
Trying multiple solution but didn't work (autocomplete = "off" for the form and for the input fields)
any idea ?

**Comment by chamerling** [comment]
Sorry I did not saw your message. I guess that the solution was just a max-width issue. Please mention me next time, or ping me on Twake

**Comment by oubchid** [comment]
> Sorry I did not saw your message. I guess that the solution was just a max-width issue. Please mention me next time, or ping me on Twake

Thanks, @chamerling, I will do next time. 
Btw, I resolved the second part of the issue (the button close of a tag), I was asking about the browser autofill part

**Comment by chamerling** [comment]
So the button close tag is a CSS max-width issue, it could have been simpler than the solution you provided.
For the autofill, TBH I do not know

**Comment by tlle14** [comment]
Thank @oubchid 
Retest pass on Chrome, Firefox Ubuntu
![image](https://user-images.githubusercontent.com/69950655/103759118-c996c980-5045-11eb-934a-8dfea9bea415.png)
