### ISSUE TITLE
Mailboxes on OpenPaas is unordered

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-inbox#230]
# Actual Result
On OpenPaas, mailboxes are not be sorted by any rules.
![Peek 2020-10-28 17-30](https://user-images.githubusercontent.com/69950655/97424579-7e748200-1943-11eb-89ed-62e07c582db9.gif)

# Expected Result
Mailboxes on OpenPaas should be sorted (by name or by create time...)

# Environment
DEV environment

**Comment by rouazana** [comment]
I don't understand the issue. Mailbox are well sorted (by "ascii" order). What would you expect exactly?

**Comment by tlle14** [comment]
> I don't understand the issue. Mailbox are well sorted (by "ascii" order). What would you expect exactly?

Hi @rouazana , please see this below images:
![screenshot_46](https://user-images.githubusercontent.com/69950655/97521584-73b3fe80-19d0-11eb-993f-7f56caccd722.png)
![screenshot_45](https://user-images.githubusercontent.com/69950655/97521597-79a9df80-19d0-11eb-9f6a-1271dbc42b1d.png)

**Comment by chibenwa** [comment]
I guess openpaas orders upper case first, then lower case - then applies alhabetic ordering.

It differ from TB (each MUA gets its own rule), and as such, from the image shown this would not be a bug.

**Comment by MichaelBailly** [comment]
Let's stay with the current case-sensitive ordering and let's wait for the users feedback.

**Comment by tlle14** [comment]
This is not a valid issue.
