### ISSUE TITLE
Unable to load identities

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-inbox#234]
![2020-10-29_14-59](https://user-images.githubusercontent.com/53081477/97541876-732f5e00-19f8-11eb-8a61-9dc83431ea2f.png)
![2020-10-29_14-58](https://user-images.githubusercontent.com/53081477/97541887-775b7b80-19f8-11eb-9ad9-7a55d884e116.png)

**Comment by chibenwa** [comment]
What was wrong by the way?

**Comment by tlle14** [comment]
> What was wrong by the way?

I don't know. The day after we could test without any response about the fix.
