### ISSUE TITLE
Error while loading forwarding settings!

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-inbox#235]
![2020-10-29_16-11](https://user-images.githubusercontent.com/53081477/97548326-90b4f580-1a01-11eb-8e99-e267c70741dc.png)

**Comment by tlle14** [comment]
Forwarding feature is working now
![image](https://user-images.githubusercontent.com/69950655/99769315-b92f9b80-2b38-11eb-91ba-abc0748b387e.png)
