### ISSUE TITLE
Opening a read Email still mark it as read

### ISSUE THREAD

**Issue by chibenwa** [OpenPaaS-Suite/esn-frontend-inbox#245]
# Current behavior

Given an INBOX page
And network tracking tab open
When I open an email already marked as read
Then the network tabs report a useless "mask as read query"

# Expected behavior

INBOX should not issue mark as read "getMessages" requests

# Impact

Unneeded **setMessages** requests hqrms performances

# Environment

openpaas.linagora.com

**Comment by tlle14** [comment]
Thank @chibenwa  for the issue report. 
Retest pass on Production. No change to read call when open a read email.
