### ISSUE TITLE
Saving draft reads all  mailboxes

### ISSUE THREAD

**Issue by chibenwa** [OpenPaaS-Suite/esn-frontend-inbox#247]
Each time I save a draft, a getMailboxes call seems to be made.

I would infer that this is to get the id of the draft mailbox. Do you confirm?

Given that the mailbox list is already known and that the draft mailbox cannot be deleted, this call is wasteful.

**Comment by chibenwa** [comment]
Any follow up / ETA on this?

**Comment by chibenwa** [comment]
Any follow up / ETA on this?

**Comment by alagane** [comment]
The library used make this request here https://ci.linagora.com/linagora/lgs/openpaas/jmap-draft-client/blob/master/lib/client/Client.js#L677

**Comment by alagane** [comment]
Merge request related: https://github.com/OpenPaaS-Suite/esn-frontend-inbox/pull/284

**Comment by tlle14** [comment]
Thank @oubchid 
Retest pass!
