### ISSUE TITLE
Polling delay configuration

### ISSUE THREAD

**Issue by chibenwa** [OpenPaaS-Suite/esn-frontend-inbox#248]
## why?

Inbox polls latest messages and refreshes the mailbox list every minute.

This is very costly, especially for users with many mailboxes.

This cause the webmail to generate more (×10) cassandra occupation than imap.

## expected results

I expect a reduction of backend generated ios by smarter choices of the polling policy (while waiting for the PUSH implementation.

## The original sin

The polling try to mimic real time push. The polling period is too long for the user to think he uses a real time system.

He likely would accept longer pull periods. For instance getting new mails while comuting accross tabs.

## Ideas

1. Pulling mailboxes less often. If not, not at all!

Maybe just refreshing counts upon message moves for source & target mailboxes. Maybe keep polling only inbox.

Another less agressive way around is to increase the mailbox polling delay, say to 10-15 minutes.

90% of jmap cassandra db occupation is generated by get mailboxes (as all mailboxes are fetched all the time z some people have up to 800 mailboxes (!!!) )

2. Making polling configurabe.

And abandon the idea that polling allows to do real time.

And thus configure higher defaults.

Note that configuration allow quicker responses, say if a production plateform do not handle the load, and is imo a MUST HAVE.

## Expected outcome

Decrease of backend  cassandra db occupations. I expect similar db usage than those of the imap protocol.

## scope of the proposals

Temporary, while waiting for THE push.

**Comment by MichaelBailly** [comment]
Edit:

what we will implement:

- keep the same polling interval for the list of emails inside a mailbox
- decrease polling for the list of mailboxes
