### ISSUE TITLE
Answer/Forward does unecessary message reads

### ISSUE THREAD

**Issue by chibenwa** [OpenPaaS-Suite/esn-frontend-inbox#251]
```
Given I have a message opened
When I click the answer button
Then INBOX performs another backend read on the very same message despite having all the information needed
```

See the following video:

![inbox-too-much-msg-read-2020-11](https://user-images.githubusercontent.com/6928740/99329359-9e4af600-28b0-11eb-88f7-07d78462d60b.gif)

**Comment by chibenwa** [comment]
Any follow up / ETA on this?

**Comment by chibenwa** [comment]
Any follow up / ETA on this?

**Comment by tlle14** [comment]
Thank @oubchid 
Retest pass!
