### ISSUE TITLE
INBOX 'in-mailbox' search does 8 getMessageList calls!

### ISSUE THREAD

**Issue by chibenwa** [OpenPaaS-Suite/esn-frontend-inbox#252]
```
When I type toto in the little mailbox search bar
Then 1 getMessageList request is done for text 't'
And then 7 more for text 'toto'
A lot of extra getMessages calls are made too
```

I expect:
 - A. That auto-completes is disabled to avoid needless expensive full text search queries on indexed data not indexed to handle that (this is both expensive and useless)
 - B. Try to do just one query for a given payload...

And as always now a video

![inbox-mbx-search-2020-11-17-0853](https://user-images.githubusercontent.com/6928740/99334165-419d0a80-28b3-11eb-827b-bbddebf8f8b6.gif)

**Comment by tanandy** [comment]
i dont expect to see 'toto' in a gherkin scenario :)
