### ISSUE TITLE
User feedback > User cannot upload a heavy file as attachment

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-inbox#254]
# Actual Result
The user cannot upload the large size attachment (about 32.6MB). It doesn't notify anything on the frontend.
![Peek 2020-11-18 17-27](https://user-images.githubusercontent.com/69950655/99518715-8d3ed980-29c3-11eb-88f2-c0cf35863905.gif)
![image](https://user-images.githubusercontent.com/69950655/99518748-97f96e80-29c3-11eb-9197-d2e402a3b9ba.png)

After unsuccessfully uploading, the email cannot be saved as a draft
# Expected Result
The user should be notified of the reason for unsuccessful uploading. 

# Environment
Production

**Comment by tlle14** [comment]
Please assign to me for retest when this fix is ready on Production

**Comment by MichaelBailly** [comment]
@tlle14 this has been fixed. Please retest after the next inbox deployment at LINAGORA.

**Comment by tlle14** [comment]
> @tlle14 this has been fixed. Please retest after the next inbox deployment at LINAGORA.

Hi Michael,
Is it ready on DEV platform? I need to verify before production.

**Comment by tlle14** [comment]
Retest pass on Desktop and Mobile
![IMG_0059](https://user-images.githubusercontent.com/69950655/103881442-05489680-510d-11eb-93d9-74e715886309.PNG)
![image](https://user-images.githubusercontent.com/69950655/103881462-0c6fa480-510d-11eb-8fff-3b5944912814.png)
