### ISSUE TITLE
Filters created without a filter name

### ISSUE THREAD

**Issue by MichaelBailly** [OpenPaaS-Suite/esn-frontend-inbox#265]
Disable possibility of sending a filter without name.

**How to reproduce**

- as a user, open the filter tab
- create a new filter, leave **filter name** empty. Fill the other information in "if a message" and "then"
- click on the save button in the upper right

**Current behaviour**
- the form is sent and the filter is created. Displayed filter values are:

![image](https://user-images.githubusercontent.com/1465817/100011805-902a3780-2dd2-11eb-9a2c-62ca61445096.png)

**Expected behaviour**
1/ the user can not send the filter creation form without a filter name
2/ The API server should not accept a request with a null filter name

Clone of https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.unifiedinbox/issues/1203

**Comment by chibenwa** [comment]
James should reject it too in the upcoming filters implementation.

**Comment by alagane** [comment]
Related pull request: https://github.com/OpenPaaS-Suite/esn-frontend-inbox/pull/281

**Comment by tlle14** [comment]
Thanks @alagane 
Retest pass
![Peek 2021-01-06 15-47](https://user-images.githubusercontent.com/69950655/103748365-96007300-5036-11eb-9fe3-f58141fa2b83.gif)
