### ISSUE TITLE
User Feedback > Replying email in sent mailbox has incorrect receipient

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-inbox#277]
# Precondition
UserA sent an email to UserB

# Actual Result
In the Sent mailbox, UserA clicks reply to the email, it opens a composer that has recipient is UserA 

![image](https://user-images.githubusercontent.com/69950655/100563935-3524a300-32f2-11eb-849b-2ff75ce19198.png)

# Expected Result
The recipient should be userB

# Environment
Production

**Comment by tlle14** [comment]
CC: @MichaelBailly

**Comment by oubchid** [comment]
@tlle14 
What is the case if we have several receipients (UserA sent an email to UserB and UserC). Should we include all of them

**Comment by rouazana** [comment]
> @tlle14
> What is the case if we have several receipients (UserA sent an email to UserB and UserC). Should we include all of them?

Yes

**Comment by fabienmoyon** [comment]
After investigation, this logic need to be done only to the sent folder and not for every folder.

So @oubchid we need to add a condition to the sent folder.

**Comment by fabienmoyon** [comment]
Already fix in dev

**Comment by tlle14** [comment]
Thank @fabienmoyon 
Retest pass!
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/fa4be195-6c32-464c-946f-d66949a9bc76)
