### ISSUE TITLE
The first email in the inbox is always clipped on page load. 

### ISSUE THREAD

**Issue by rezk2ll** [OpenPaaS-Suite/esn-frontend-inbox#286]
On first page load the first email In the list in kinda clipped until you manually scroll up. 

![IMG_20201210_145519.jpg](https://user-images.githubusercontent.com/6764881/101781205-cddbcf80-3af7-11eb-9053-7b3f11e89ded.jpg)

**Comment by alagane** [comment]
See #90

**Comment by rezk2ll** [comment]
sorry didn't see it.

closed cause duplicate of #90
