### ISSUE TITLE
Mobile > Experiments screen has an inpropriate line break

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-inbox#295]
**1. Inappropriate line break in the text "tree view"**
=> It should display in one line
 
![image](https://user-images.githubusercontent.com/69950655/102456409-af378480-4073-11eb-8e23-90c44ea2a06e.png)

**2. When disable/enable the checkbox, the notification has a line break**
=> Should change the text to be shorter

![image](https://user-images.githubusercontent.com/69950655/102456563-f0c82f80-4073-11eb-8cb1-cdb21f7673b1.png)

**Comment by fabienmoyon** [comment]
Hello @tlle14,

1. Done https://github.com/OpenPaaS-Suite/esn-frontend-inbox/issues/293

1. Hard to put a shorter sentence and it's not a requirement, display a more visible button is more important https://github.com/OpenPaaS-Suite/esn-frontend-inbox/issues/302
