### ISSUE TITLE
Mobile > Experiments screen seems to have too much text

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-inbox#296]
# Actual Result
From the Mobile view, It seems to have too much text on the screen 
![image](https://user-images.githubusercontent.com/69950655/102456901-79df6680-4074-11eb-8d13-ac7f14bb011a.png)

# Expected Result
The screen should be simplified

**Comment by fabienmoyon** [comment]
Hello @tlle14 I will close this one, we need to explain to the used what is the experimentation tab and we can't put a shorter version only for mobile, that's not our vision (be ISO on mobile and on desktop).
