### ISSUE TITLE
Excluse ics & inline images on attachment sidebar panel

### ISSUE THREAD

**Issue by MichaelBailly** [OpenPaaS-Suite/esn-frontend-inbox#314]

**Comment by fabienmoyon** [comment]
Hello James team @chibenwa and Calendar team @renaudboyer , 

I'm working on this issue and I see that for a calendar email I have a weird attachment with a `name:null` and `type: text/calendar; charset=UTF-8; method=REQUEST`

We are agree that something wrong, Is it possible to remove this wrong attachment ?

****

![Capture d’écran de 2021-02-19 09-55-43.png](https://images.zenhubusercontent.com/5f9c1883317e52f28f3396ce/727f0aba-2c18-4327-9237-18c5998e087f)

![Capture d’écran de 2021-02-19 09-57-49.png](https://images.zenhubusercontent.com/5f9c1883317e52f28f3396ce/ea91b43c-4741-4fde-8f8d-54cfb807b2f4)

```
{
blobId: "auyyzrhvibjcpmbdmfbf"
cid: null
height: null
inlinedWithCid: false
isInline: false
name: null
size: 1981
type: "text/calendar; charset=UTF-8; method=REQUEST"
width: null
},{
blobId: "eefnbficovpdeafklvqq"
cid: null
height: null
inlinedWithCid: false
isInline: false
name: "meeting.ics"
size: 1981
type: "application/ics; name=meeting.ics"
width: null
blobId: "8f7a2590-6fb6-11eb-9e0c-d3347f2641b3"
date: "2021-02-15T17:52:23Z"
hasAttachment: true
id: "8f7a2590-6fb6-11eb-9e0c-d3347f2641b3"
}
```

**Comment by chibenwa** [comment]
While this would make sense to me not exposing the ICS details somehow feels wrong.

I would agree to change stuff on James side to **not** consider ICS as attachment, effectively hidding them to the end user.

Note that in JMAP RFC-8621 this is a non question as advanced mime structure allows alternative clients to discover the ICS via the mime propoerties (that is why I consider it is OK to not consider it as an attachment)

That being said, the  `Content-Type: text/calendar` do not have a file name and thus likely should not be conidered as an attachment. The ics HAS the content disposition. We likely can keep it.

@fmoyon, what other MUA do? TB for instance displays only the ICS as an attachment.

**Comment by fabienmoyon** [comment]
Yes, if you can not consider `ICS` and `Content-Type: text/calendar` as attachment by `isInline: false` the end user will not see them and will close this issue :D

> That being said, the Content-Type: text/calendar do not have a file name and thus likely should not be conidered as an attachment. The ics HAS the content disposition. We likely can keep it.

Others display ICS as an attachment **ONLY** in the mail detail (like https://app.zenhub.com/workspaces/ft---inbox-5f9bf5a7d512f60015b11562/issues/openpaas-suite/esn-frontend-inbox/314#issuecomment-781965921) but display the ICS as an event attachment  in the mail view as this issue https://github.com/OpenPaaS-Suite/esn-frontend-inbox/issues/168.

**Comment by chibenwa** [comment]
Not TB

![Capture d’écran de 2021-02-20 08-59-15](https://user-images.githubusercontent.com/6928740/108579586-4366e600-735a-11eb-8030-becb21fe68db.png)

The text/calendar is dropped (ok) but the ICS is considered as an attachment in both side bar and detailed view.

On the implementation side, it is easy for the backend to ommit fully attachments, or to include them fully. Zombie attachment are waaay harder to implement.

**Comment by fabienmoyon** [comment]
> The text/calendar is dropped (ok) but the ICS is considered as an attachment in both side bar and detailed view. 

Yes because TB don't have the calendar event icon ;) 

> BTW INBOX can likely exclude ICS from side pannel based on the mime part content type itself.

Yes that the case regarding the ICS but can we put the `Content-Type: text/calendar` attachment as `isInline:true` because it should not be considered as an attachment.

**Comment by tlle14** [comment]
Hi @fabienmoyon 
Retest failed! The ics file is still displaying in the attachment list
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/eeb1cb9f-eb92-45e0-9ada-e7d3115ee0f3)
