### ISSUE TITLE
User Feedback > Cannot paste the plaint text into the composer

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-inbox#323]
# Actual Result
User cannot paste the plain text into the composer or using Ctrl+Shift+V.
![Peek 2021-01-08 17-34](https://user-images.githubusercontent.com/69950655/104005581-ec58e780-51d7-11eb-81cf-9ebf90837896.gif)

# Expected Result
User should be able to paste the text without formating

# Environment
Production
Browsers on Ubuntu/Windows

**Comment by alagane** [comment]
I had not the "paste without formatting" button, but I reproduced it copying a text from gedit, or copying text without formatting.

**Comment by oubchid** [comment]
Revert done here
https://github.com/OpenPaaS-Suite/esn-frontend-inbox/pull/332

**Comment by tlle14** [comment]
Thank @oubchid  @alagane 
Retest pass on Production
![Peek 2021-01-25 10-31](https://user-images.githubusercontent.com/69950655/105658210-a353a380-5ef8-11eb-938b-c466505a60df.gif)
