### ISSUE TITLE
Display Sent items by TO and not FROM

### ISSUE THREAD

**Issue by fabienmoyon** [OpenPaaS-Suite/esn-frontend-inbox#336]
#### CURRENT

![Capture_du_2018-05-22_16-33-53](https://user-images.githubusercontent.com/11298249/105483006-7d848f80-5ca9-11eb-8678-78524894f1cf.png)

#### EXPECTED 

Display Sent items by TO like it was done before

#### RELATED ISSUES 

- https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.unifiedinbox/issues/868
- https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.unifiedinbox/issues/884

**Comment by tlle14** [comment]
Thank @fabienmoyon 
Retest pass!

![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/9d757e95-309a-4514-99ce-c71c2a5a1636)
