### ISSUE TITLE
on hover an email show the checkbox to be able to do an action on it

### ISSUE THREAD

**Issue by fabienmoyon** [OpenPaaS-Suite/esn-frontend-inbox#338]
#### Current

On hover an email, the checkbox is not show. The checkbox is show on hover of the avatar. 

![Capture d’écran de 2021-01-25 16-05-07](https://user-images.githubusercontent.com/11298249/105723491-212ea380-5f27-11eb-924a-22f5b8f8e95a.png)

#### Expected

On hover an email show directly the checkbox to be able to do an action on it

![Capture d’écran de 2021-01-25 16-04-22](https://user-images.githubusercontent.com/11298249/105723420-0ceaa680-5f27-11eb-8090-115fc5dfe5aa.png)

**Comment by tlle14** [comment]
Thank @fabienmoyon 
Retest pass
![Peek 2021-02-25 15-24.gif](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/9011b004-7e10-4d6a-aa3b-7f77d5239348)
