### ISSUE TITLE
Replace the legacy application grid with a web component

### ISSUE THREAD

**Issue by MichaelBailly** [OpenPaaS-Suite/esn-frontend-inbox#34]
The new ["static" application grid](https://ci.linagora.com/linagora/lgs/openpaas/esn/-/wikis/Frontend-Split/Stage-2/Header-Bar#step-1-static-content) is a web component.

* include the application grid web component in Inbox (the build, not the sources)
* add an environement variable APP_GRID_ITEMS that is injected in the web component HTML, either directly or through AngularJS (the more simple and fast)

```
APP_GRID_ITEMS="...json..." npm run serve|build:dev
```

**Comment by chamerling** [comment]
There is several ways to do it with webpack, like they do for example in VueJS application having several env files (https://cli.vuejs.org/guide/mode-and-env.html#modes)

https://webpack.js.org/plugins/environment-plugin/
https://github.com/mrsteele/dotenv-webpack

**Comment by huy-ta** [comment]
Thank you. I'll look into this tomorrow.

**Comment by huy-ta** [comment]
> There is several ways to do it with webpack, like they do for example in VueJS application having several env files (https://cli.vuejs.org/guide/mode-and-env.html#modes)
> 
> https://webpack.js.org/plugins/environment-plugin/
> https://github.com/mrsteele/dotenv-webpack

Thanks. Something like `dotenv-webpack` is definitely the way to go. From the many times I've done it before, it is quite easy and flexible. Defining environment variables inside an npm command can be a bit cumbersome, and requires the use of `cross-env` as well.
