### ISSUE TITLE
as a user, I want reply actions more visible

### ISSUE THREAD

**Issue by fabienmoyon** [OpenPaaS-Suite/esn-frontend-inbox#345]
#### DESCRIPTION 

When I open an email, sometimes I just want to answer to 1 person or transfer to another : the problem is that the buttons are on the bottom of the mail, which can be disruptive when the email is long because I must scroll down the entire conversation.

Two solution for that :
1) make a fixed bottom bar with the buttons
2) add the two options with the "answer to all" in the right corner

![image-1605604875](https://user-images.githubusercontent.com/11298249/106611790-aab62500-6568-11eb-8e8c-5056bc64491d.png)

#### EXPECTED

1) Like asked maybe fixed the bottom bar but need to be validate for a thread. 

2) Change the `reply actions` icon to a better visibility

![Capture d’écran de 2021-02-02 18-28-16](https://user-images.githubusercontent.com/11298249/106638774-85cfab00-6584-11eb-9bf6-5547a0a4369d.png)

TO

maybe update bootstrap popover to https://material.angularjs.org/1.1.26/demo/menu

![Capture d’écran de 2021-02-17 10-04-15.png](https://images.zenhubusercontent.com/5f9c1883317e52f28f3396ce/fe72062b-03d2-4d1c-a415-99f4d8501b8d)

![Capture d’écran de 2021-02-02 18-26-31](https://user-images.githubusercontent.com/11298249/106638524-41440f80-6584-11eb-81b0-ce4584c984e8.png)

![Capture d’écran de 2021-02-02 18-26-37](https://user-images.githubusercontent.com/11298249/106638521-40ab7900-6584-11eb-8fda-82cf39dc00f6.png)

**Comment by tlle14** [comment]
Thank @fabienmoyon 
Retest pass!
![Peek 2021-03-09 14-07.gif](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/f5f09653-e5b6-4067-9b30-c6d276056cab)
