### ISSUE TITLE
As a user I want to have a `mark as` more user friendly

### ISSUE THREAD

**Issue by fabienmoyon** [OpenPaaS-Suite/esn-frontend-inbox#346]
#### Description

When I select an unread message, I have the opportunity to "mark it as read" in the top right corner : But when I select an already read message, the icon stay the same => It can be useful to allow the user to "mark it as unread" when an already read message is selected !

just add a condition :
- if you select only read messages : the button is "unread"
- if you select only unread messages : the button is "read"
- if you select read and unread messages : both buttons appears

![image-85](https://user-images.githubusercontent.com/11298249/106611772-a7bb3480-6568-11eb-89cd-6a8a2f4393a8.png)

**Comment by tlle14** [comment]
Thank @fabienmoyon 
Retest pass!
![Peek 2021-03-09 14-15.gif](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/e8ead529-42c7-471a-b4c0-a491e0d5653f)
