### ISSUE TITLE
Convenient menu got a collapse UI on Firefox

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-inbox#363]
# Actual Result
Hover on the email, convenient menu is displaying with a collapse UI
![image](https://user-images.githubusercontent.com/69950655/108799047-e8372c80-75c1-11eb-8778-4332ba5200bc.png)

# Expected Result
The convenient menu should display with a correct UI
![image](https://user-images.githubusercontent.com/69950655/108799401-cd18ec80-75c2-11eb-92c4-b04e525cb280.png)

# Environment
DEV platform
Browser: Firefox

**Comment by tlle14** [comment]
No more issue after dev platform is up to date
![Peek 2021-02-26 10-57](https://user-images.githubusercontent.com/69950655/109253064-87a62a80-7821-11eb-84ee-e30c96cb0518.gif)

**Comment by fabienmoyon** [comment]
Already fix here https://github.com/OpenPaaS-Suite/esn-frontend-inbox/pull/369
