### ISSUE TITLE
User Feedback > Put the forwarding button on the top bar for more realizable

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-inbox#375]
# Actual Result
Recently, the forwarding button is on the bottom bar or hidden in the menu, it's not convenient for the user to have a quick action.
![image](https://user-images.githubusercontent.com/69950655/109625670-2dcf9880-7b72-11eb-9d96-33b09b3ec498.png)

# Expected Result
The user proposes to put the forward button next to the reply button on the top bar. 
Please work with our UX designer for the change

# Environment
OpenPaas on Web
Production

**Comment by fabienmoyon** [comment]
Already done in this issue ;) https://github.com/OpenPaaS-Suite/esn-frontend-inbox/issues/345
