### ISSUE TITLE
lodash dependency not imported correctly

### ISSUE THREAD

**Issue by alagane** [OpenPaaS-Suite/esn-frontend-inbox#394]
On the project, lodash is not a direct dependency. There are different version from the project dependencies (if you try `npm list lodash`), the `2.4.1` (the one we want, from https://github.com/OpenPaaS-Suite/esn-frontend-common-libs/blob/main/package.json) or the `4.17.21` (not working on the project, used by other dependencies).

NPM will install one of the versions (and put it in the `node_modules/lodash` directory), and the other will be put in `node_modules/<dependency-using-other-lodash-version>/node_modules/lodash`. If the chosen version is not `2.4.1`, then you should have an error when running `npm run test`:
```
Module not found: Error: Can't resolve '[...]/esn-frontend-inbox/node_modules/lodash/dist/lodash.js' in '[...]/esn-frontend-inbox/src/linagora.esn.unifiedinbox/app/services/models'
```

A simple solution would be to use lodash from `node_modules/<dependency-using-other-lodash-version>/node_modules/lodash` instead of from `node_modules/lodash` but it would not work when the version is the good one.

Or we could import lodash directly.

We also have to check if the problem happens on other repositories.

Quick local workaround if you stumble on the problem : `npm i --no-save lodash@2.4.1`

**Comment by oubchid** [comment]
For my side I didn't get this error, and all tests pass !
Do you have this package installed globally on your machine ? 

![image](https://user-images.githubusercontent.com/7097550/111977979-b1dac780-8b03-11eb-9045-ae56d0d9dd64.png)

Otherwise, we can check with others 
@fabienmoyon

**Comment by alagane** [comment]
Should also happen on:
https://github.com/OpenPaaS-Suite/esn-frontend-contacts
https://github.com/OpenPaaS-Suite/esn-frontend-inbox-linshare
https://github.com/OpenPaaS-Suite/esn-frontend-calendar

**Comment by alagane** [comment]
@chamerling if you can give a quick look on this issue, do you think adding the right version of lodash as a devDependency on each project with this problem is the best solution?

**Comment by fabienmoyon** [comment]
@renaudboyer :eyes:
