### ISSUE TITLE
Backlog Refinement for Sprint 10

### ISSUE THREAD

**Issue by alagane** [OpenPaaS-Suite/esn-frontend-inbox#409]
Create issues and refine issues for:

Email changes (like it was done for Mailbox)
How to do with pagination

Websocket if authentication problems fixed on James.

OpenPaas administration

Email counters up to date

env/openpaas.js for building individual SPAs

**Comment by chibenwa** [comment]
> Websocket if authentication problems fixed on James.

Fixed. I think using the ticket system auth is an issue of its own.

BTW how are we regarding positionning Accept version on all requests?
