### ISSUE TITLE
All attachments are not shown when clicking "Show emails with attachments" icon

### ISSUE THREAD

**Issue by TuanQA92** [OpenPaaS-Suite/esn-frontend-inbox#73]
Pre-condition:  There are emails with attachments  in the INBOX 

Reproduce steps: 
- Go to https://dev.open-paas.org/ and login user A 
- Go to the new SPA URL : https://dev.open-paas.org/inbox/
- Click on "Show emails with attachments" icon 
- Verify issue 

Actual Results:  All attachments are not shown  
![image](https://user-images.githubusercontent.com/69950706/90752565-c357b900-e301-11ea-8b57-5ddea9b50c67.png)

Expected Results:  All attachment should be shown if there are emails with attachments in the INBOX

**Comment by huy-ta** [comment]
## DoD

#### What I have done

I've fixed the issue via http://github.com/OpenPaaS-Suite/esn-frontend-inbox/pull/117. Now the attachments are shown when clicking the "Show emails with attachments" icon.

#### Environment tested

- Browser: Chrome (Desktop - Ubuntu)
- Mode: Dev, Production

@tlle14 You might want to test this on https://dev.open-paas.org/inbox/ after a few hours. Once verified, please close this issue.

**Comment by tlle14** [comment]
Thank @huy-ta 

Retest pass!

![image](https://user-images.githubusercontent.com/69950655/92460112-c43d8580-f1f1-11ea-82d7-bd6729040bbc.png)
