### ISSUE TITLE
Unable to move to email 

### ISSUE THREAD

**Issue by TuanQA92** [OpenPaaS-Suite/esn-frontend-inbox#74]
Reproduce steps:
- Select to go to email's detail in the INBOX 
- Click on "MOVE TO" icon
- Verify issue

Actual Results: Unable to move to email and it displays the error in the Console tab. 
![image](https://user-images.githubusercontent.com/69950706/90847614-129af980-e395-11ea-84b9-dbafed1d890e.png)

Expected Results:  Please help to investigate this and fix to able to move to email 

Tested on Go to https://dev.open-paas.org/  and using Chrome/Firefox on Ubuntu

**Comment by tlle14** [comment]
Thank @huy-ta 

Retest pass

![Peek 2020-08-27 11-32](https://user-images.githubusercontent.com/69950655/91384595-33fa5a80-e859-11ea-923c-5af51db7db0c.gif)
