### ISSUE TITLE
The user in the "From" field disappears after clicking the REOPEN the draft

### ISSUE THREAD

**Issue by TuanQA92** [OpenPaaS-Suite/esn-frontend-inbox#75]
#### Reproduce steps

- Go to https://dev.open-paas.org/ and login user A
- Go to the SPA URLs: https://dev.open-paas.org/inbox/A
- Open composer
- Click DELETE icon
- System shows message 
- Click on "REOPEN" 
- Verify issue 

#### Actual Results

 The user in the "From" field disappears after clicking the REOPEN  draft
![image](https://user-images.githubusercontent.com/69950706/90750063-7c1bf900-e2fe-11ea-815d-58a9f04ed77d.png)

#### Expected Results

Keep user in the "From" field aftẻ clicking the REOPEN draft

**Comment by tlle14** [comment]
Retest pass on DEV platform
