### ISSUE TITLE
Vacation > Time Picker is not shown when I focus on textbox field  (End time)

### ISSUE THREAD

**Issue by TuanQA92** [OpenPaaS-Suite/esn-frontend-inbox#78]
Reproduce steps:
-  Go to Configuration in the INBOX module  
- Vacation is to Activated 
- Focus pointer mouse to the textbox field  (No end time)
- Verify issue 

Actual Results: Time Picker is not shown when focusing on this field.
![image](https://user-images.githubusercontent.com/69950706/90862637-eba1ef00-e3b7-11ea-86f1-1b780dfefb8d.png)

Expected Results: It should be shown so that I can select a time for this

Tested on   https://dev.open-paas.org/ and using chrome & firefox on ubuntu

**Comment by tlle14** [comment]
Thanks @huy-ta 

Retest pass

![image](https://user-images.githubusercontent.com/69950655/91382625-50e05f00-e854-11ea-9277-13a0afcd4d5e.png)

![image](https://user-images.githubusercontent.com/69950655/91382674-72414b00-e854-11ea-9329-00b17a2bc8f4.png)
