### ISSUE TITLE
Blank screen when opening configuration 

### ISSUE THREAD

**Issue by TuanQA92** [OpenPaaS-Suite/esn-frontend-inbox#79]
#### Reproduce steps

- Go to Configuration in the INBOX module 
- Verify issue 

Actual Results:  Blank screen when opening configuration 
![image](https://user-images.githubusercontent.com/69950706/90864602-2bb6a100-e3bb-11ea-9d7e-1825762d5572.png)

#### Expected Results: 

After opening the configuration setting, it should be focused on the Vacation tab and shown fully the information in this tab. 

Tested on https://dev.open-paas.org/

**Comment by tlle14** [comment]
Thank @oubchid 
Retest pass on Production
![Peek 2021-01-07 18-05](https://user-images.githubusercontent.com/69950655/103885743-10062a00-5113-11eb-9318-4e416e130a18.gif)
