### ISSUE TITLE
Filter > The message "Filters set"  is not localized in FR/ Russia/Chinese/Vietnamese 

### ISSUE THREAD

**Issue by TuanQA92** [OpenPaaS-Suite/esn-frontend-inbox#83]
Reproduce steps:

- Go to INBOX -> Configuration 
- Create a filter 
- Verify issue

Actual results: System is displaying the message "Filters set" in English while I am setting for the system in FR/Russia/Chinese/Vietnamese 
![Screenshot from 2020-08-24 15-00-48](https://user-images.githubusercontent.com/69950706/91019129-b8ab6580-e61a-11ea-99bf-d02e570eaeb9.png)

Expected Results: Localization according to the set language

**Comment by tlle14** [comment]
Thank @oubchid 
Retest pass on Production
