### ISSUE TITLE
Translation issue in INBOX 

### ISSUE THREAD

**Issue by TuanQA92** [OpenPaaS-Suite/esn-frontend-inbox#84]
1. Hint text  "Search in emails"  in the textbox search field 

![image](https://user-images.githubusercontent.com/69950706/91023230-7b49d680-e620-11ea-99d7-db6d5ff13969.png)

Actual : Display the text "Search in emails" in English 
Expected: Should display in Chinese 

2. Go to Configuration > Filter

![image](https://user-images.githubusercontent.com/69950706/91023171-69683380-e620-11ea-9fae-329234c1bd0d.png)

Actual: 
- Text " You can create rules that will tell OpenPaaS how to handle incoming messages. You choose both the condition that trigger a rule and the actions the rule will take. Rules will run in order shown in the list below, starting with the rule at the top" is in English language
- Text "No Rule" is in English language 

Expected: Should display in Chinese 

3.  When hovering to Linshare icon in the composer -> Tooltip is in English  (Happens in all language) 
![image](https://user-images.githubusercontent.com/69950706/91024544-4dfe2800-e622-11ea-9c73-c7420d645447.png)

Actual:  Text " Bowser my  files in Linshare " is in English 
Expected:  Localization according to the set language 

4. Empty older with encoded symbol

![image](https://user-images.githubusercontent.com/69950655/91417830-8e0c1780-e87b-11ea-9105-0c694c32bea9.png)

Actual: "Did you know you can drag &amp; drop messages to this folder? Give it a try!"
Expected: Did you know you can drag & drop messages to this folder? Give it a try!

**Comment by oubchid** [comment]
Hi @TuanQA92 

1. You're right this will be fixed.
2. This is already fixed I obtain the good translation !
3. Can you please send us translations text for `Bowser my files in Linshare` ?

**Comment by oubchid** [comment]
PR :https://github.com/OpenPaaS-Suite/esn-frontend-inbox/pull/226

**Comment by tlle14** [comment]
**Issue 1: Pass**
![image](https://user-images.githubusercontent.com/69950655/99773521-26dec600-2b3f-11eb-8f7f-a83f553a10fd.png)

**Issue 2: Pass**
![image](https://user-images.githubusercontent.com/69950655/99773644-57266480-2b3f-11eb-9824-fe92e1919fba.png)

**Issue 3: Pass**
![image](https://user-images.githubusercontent.com/69950655/99773887-aa001c00-2b3f-11eb-8b5b-2c1282ee6267.png)

Issue 4: Pass
![image](https://user-images.githubusercontent.com/69950655/99773971-c8feae00-2b3f-11eb-9d93-527c20261199.png)
![image](https://user-images.githubusercontent.com/69950655/99774030-dddb4180-2b3f-11eb-9cba-b79e8e382727.png)

Thank youuuuu
